//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aeropuerto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public int idVuelo { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<int> NumeroVuelo { get; set; }
    }
}
